---
name: Bump CLI Formula

on:
  push:
    tags:
      - cli-v**
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-desktop-cask:
    name: Update Bitwarden CLI Formula
    runs-on: macos-11
    steps:
      - name: Login to Azure
        uses: Azure/login@6453efca84e884a7848c9681f6515bf7732bd20b
        with:
          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@b5c723b9ac7870c022b8c35befe620b7009b336f
        with:
          keyvault: "bitwarden-prod-kv"
          secrets: "brew-bump-workflow-pat"

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@dd221ff435f42fa8102b5871bb1929af9d76476c
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{ steps.retrieve-secrets.outputs.brew-bump-workflow-pat }}
          org: bitwarden
          tap: Homebrew/homebrew-core
          cask: bitwarden-cli
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
          force: false
          dryrun: true
