---
name: Chromatic

on:
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Node
        uses: actions/setup-node@348e00800850ca70958af8888ebdb3cce7cbcddc  # v2.1.5
        with:
          node-version: "16"

      - name: Checkout repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v2.3.4
        with:
          fetch-depth: 0

      - name: Cache npm
        id: npm-cache
        uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c  # v2.1.6
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-npm-chromatic-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@076a689abb129d219378bcd5e7d7fb13f320854b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          onlyChanged: true
          externals: "[\"components/**/*.scss\", \"components/tailwind.config*.js\"]"
